run:
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - lll
  disable:
    - typecheck
    - contextcheck
  presets:
    - bugs

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
  staticcheck:
    checks:
      - "all"
  govet:
    enable:
      - nilness
      - defers
      - lostcancel
      - bools

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - lll
    - path: .go
      linters:
        - typecheck
        - contextcheck
        - exhaustive
