name: Go lint, test
description: Lint and test go code

inputs:
  working-dir:
    required: false
    default: lambdas/go

runs:
  using: composite
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        token: ${{ github.token }}
        go-version-file: ${{ inputs.working-dir }}/go.mod
        cache-dependency-path: ${{ inputs.working-dir }}/go.mod
        cache: true

    - name: Set path
      shell: bash
      run: |
         mkdir -p "$PWD/bin"
         echo "$PWD/bin" >> $GITHUB_PATH

    - name: Install buf
      # TODO: checkout the new buf action: https://github.com/bufbuild/buf-action
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    # TODO: Get these from the dependency versions
    - name: Install Dependencies
      shell: bash
      run: make dependencies-install-go
    # - name: Install stringer
    #   shell: bash
    #   run: go install golang.org/x/tools/cmd/stringer@v0.27.0
    #
    # - name: install mockery
    #   shell: bash
    #   run: |
    #     tar -xz -C bin -f <(curl -Ls https://github.com/vektra/mockery/releases/download/v2.25.0/mockery_2.25.0_Linux_x86_64.tar.gz)

    - name: generate proto stubs
      shell: bash
      run: make generate-go

    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: go test ./...

    - name: Run go vet
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: go vet ./...

    - name: Run Staticcheck
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        install-go: false
        cache-key: ubuntu-${{ steps.setup-go.outputs.go-version }}
        checks: "all -ST1000 -ST1003"
        working-directory: ${{ inputs.working-dir }}
