name: Deploy react to S3

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: undefined
      deploy:
        required: false
        type: boolean
        default: false


env:
  S3_BUCKET_NAME: conflict-nightlight-frontend
  DOMAIN_NAME: conflictnightlight.com

jobs:
  build-deploy-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: REACT_APP_MAPBOX_TOKEN=${{ secrets.REACT_APP_MAPBOX_TOKEN }} REACT_APP_VERSION=${{ inputs.version }} yarn build

      - name: Configure AWS
        if: ${{ inputs.deploy == true }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Push to S3
        if: ${{ inputs.deploy == true }}
        run: aws s3 cp build s3://${{ env.S3_BUCKET_NAME }}/ --recursive

      - name: Invalidate Cloudfront Cache
        if: ${{ inputs.deploy == true }}
        run: aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[0]=='${{ env.DOMAIN_NAME }}'].Id | [0]" --output text) --paths "/*"
