name: Go lint, test

on:
  workflow_call

env:
  WORKING_DIR: lambdas/go

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        id: setup-go
        with:
          token: ${{ github.token }}
          go-version-file: ${{ env.WORKING_DIR }}/go.mod
          cache-dependency-path: ${{ env.WORKING_DIR }}/go.mod
          cache: true

      - run: |
          mkdir -p "$PWD/bin"
          echo "$PWD/bin" >> $GITHUB_PATH

      - run: go install golang.org/x/tools/cmd/stringer@latest

      - name: install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: install mockery
        run: |
          tar -xz -C bin -f <(curl -Ls https://github.com/vektra/mockery/releases/download/v2.25.0/mockery_2.25.0_Linux_x86_64.tar.gz)

      - name: generate proto stubs
        working-directory: .
        run: make generate-go

      - name: Test
        run: go test ./...

      - run: go vet ./...

      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          cache-key: ubuntu-${{ steps.setup-go.outputs.go-version }}
          checks: "all -ST1000 -ST1003"
          working-directory: ${{ env.WORKING_DIR }}
