name: lint proto

on:
  workflow_call

jobs:
  double-check:
    name: Check for breaking changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - run: buf format --diff --exit-code

      - run: buf generate --log-format text --template proto/buf.gen.go.yaml

      - run: buf generate --log-format text --template proto/buf.gen.python.yaml

      - uses: bufbuild/buf-lint-action@v1
