name: On push main

on:
  push:
    branches:
      - main

      # TODO: inject variables to go and react, for the file shared with the CDN
env:
  FRONTEND_MAP_OPTIONS_JSON: "conflict-nightlight-map-options"

jobs:
  image-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.image-tag }}
    steps:
      - id: set-image-tag
        run: echo "image-tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  go-zip-builder-and-deployer:
    name: Build and deploy go zip
    runs-on: ubuntu-latest
    needs:
      - image-tag
    strategy:
      matrix:
        name: [ map_controller, map_publisher ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-deploy-go
        with:
          name: ${{ matrix.name }}
          zip-tag: ${{ needs.image-tag.outputs.image-tag }}
          deploy: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  python-image-builder-and-deployer:
    name: Build and deploy python docker
    runs-on: ubuntu-latest
    needs:
      - image-tag
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-deploy-docker-image
        with:
          deploy: true
          image-tag: ${{ needs.image-tag.outputs.image-tag }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  react-image-builder-and-deployer:
    name: Build and push react to S3
    runs-on: ubuntu-latest
    needs:
      - image-tag
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-deploy-react
        with:
          deploy: true
          version: ${{ needs.image-tag.outputs.image-tag }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          react-app-mapbox-token: ${{ secrets.REACT_APP_MAPBOX_TOKEN }}
          google-tag: ${{ secrets.GOOGLE_TAG }}
