name: On pull request main

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-lint-test:
    name: Lint and test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-test-python

  python-image-builder:
    name: Build python image
    runs-on: ubuntu-latest
    needs: python-lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-deploy-docker-image

  go-lint-test:
    name: Lint and test go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-test-go

  go-builder:
    name: Build go
    needs: go-lint-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ map_controller, map_publisher ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-deploy-go
        with:
          name: ${{ matrix.name }}

  react-builder:
     name: Build react
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/build-deploy-react

  proto-linter:
    name: Lint proto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-proto

  # https://github.com/community/community/discussions/4324
  can-deploy:
    runs-on: ubuntu-latest
    needs:
      - python-lint-test
      - python-image-builder
      - go-lint-test
      - go-builder
      - react-builder
      - proto-linter
    if: always()
    steps:
      - name: successful
        if: ${{ !contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 0
      - name: failing
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
