name: On pull request main

on:
  pull_request:
    branches:
      - main

jobs:
  python-lint-test:
    uses: ./.github/actions/lint-test-python.yml

  python-image-builder:
    needs: python-lint-test
    uses: ./.github/actions/build-deploy-docker-image.yml

  go-lint-test:
    uses: ./.github/actions/lint-test-go.yml

  go-builder:
    needs: go-lint-test
    strategy:
      matrix:
        name: [ map_controller, map_publisher ]
    uses: ./.github/actions/build-deploy-go.yml
    with:
      name: ${{ matrix.name }}

  react-builder:
    uses: ./.github/actions/build-deploy-react.yml

  proto-lint:
    uses: ./.github/actions/lint-proto.yml

  # https://github.com/community/community/discussions/4324
  can-deploy:
    runs-on: ubuntu-latest
    needs:
      - python-lint-test
      - python-image-builder
      - go-lint-test
      - go-builder
      - react-builder
      - proto-lint
    if: always()
    steps:
      - name: successful
        if: ${{ !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: failing
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
